/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exemple;
import exemple.Util;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void smokeTest() {
        assertTrue(true);
    }

    @Test void deepThoughtTest() {
        assertEquals(Util.theAnswer(), 42);
    }
}
